from __future__ import annotations

import json
import re
import shutil
import unicodedata
from dataclasses import dataclass
from pathlib import Path


MARKER = ".book2skill-generated.json"
CHAPTER_PATTERNS = (
    re.compile(r"^第\s*(\d+)\s*章\s*[:：、.．-]?\s*(.+?)\s*$"),
    re.compile(r"^chapter\s+(\d+)\s*[:：.\-]?\s*(.+?)\s*$", re.IGNORECASE),
    re.compile(r"^(\d+)\s*[、．.]\s+(.+?)\s*$"),
)
SECTION_RE = re.compile(r"^(\d+(?:\.\d+)+)\s+(.+?)\s*$")


@dataclass(frozen=True)
class Chapter:
    number: int
    title: str
    start: int
    end: int


@dataclass(frozen=True)
class Heading:
    number: str
    line: str
    index: int
    level: int


@dataclass(frozen=True)
class BuildResult:
    references: Path
    chapters: int
    files: tuple[Path, ...]


def skill_slug(stem: str) -> str:
    normalized = unicodedata.normalize("NFKD", stem)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_text).strip("-")
    return f"{slug or 'book'}-skill"


def safe_name(value: str) -> str:
    value = re.sub(r'[\\/:*?"<>|]', "_", value.strip())
    value = re.sub(r"\s+", " ", value).strip(" .")
    return value or "untitled"


def _match_chapter(line: str) -> tuple[int, str] | None:
    for pattern in CHAPTER_PATTERNS:
        match = pattern.fullmatch(line.strip())
        if match:
            return int(match.group(1)), match.group(2).strip()
    return None


def chapters(lines: list[str]) -> list[Chapter]:
    markers = [
        (number, title, index)
        for index, line in enumerate(lines)
        if (matched := _match_chapter(line))
        for number, title in [matched]
    ]
    return [
        Chapter(number, title, start, markers[i + 1][2] if i + 1 < len(markers) else len(lines))
        for i, (number, title, start) in enumerate(markers)
    ]


def _looks_like_heading(title: str, next_line: str) -> bool:
    if not title or len(title) > 160 or "=" in title or title == "节":
        return False
    if "。" in title or next_line.lstrip().startswith("（"):
        return True
    if re.fullmatch(r"[（(][^()（）]+[）)]", next_line.strip()):
        return True
    return len(title) <= 80 and any(character.isalpha() for character in title)


def _headings(lines: list[str], chapter: Chapter) -> list[Heading]:
    found: list[Heading] = []
    prefix = f"{chapter.number}."
    for index in range(chapter.start + 1, chapter.end):
        match = SECTION_RE.fullmatch(lines[index].strip())
        if not match or not match.group(1).startswith(prefix):
            continue
        next_line = lines[index + 1] if index + 1 < chapter.end else ""
        if _looks_like_heading(match.group(2).strip(), next_line):
            number = match.group(1)
            found.append(Heading(number, lines[index].strip(), index, number.count(".")))
    return found


def _title(line: str) -> str:
    match = SECTION_RE.fullmatch(line.strip())
    if not match:
        return "untitled"
    return match.group(2).split("。", 1)[0].strip()


def _split_heading(line: str, number: str) -> list[str]:
    prefix = number + " "
    if not line.startswith(prefix) or "。" not in line:
        return [line]
    left, right = line.split("。", 1)
    return [left.rstrip() + "。"] + ([right.lstrip()] if right.strip() else [])


def _children(items: list[Heading], parent_index: int) -> list[int]:
    parent = items[parent_index]
    result: list[int] = []
    for index in range(parent_index + 1, len(items)):
        item = items[index]
        if item.level <= parent.level:
            break
        if item.level == parent.level + 1 and item.number.startswith(parent.number + "."):
            result.append(index)
    return result


def _end(chapter: Chapter, items: list[Heading], index: int) -> int:
    child_indexes = _children(items, index)
    if child_indexes:
        return items[child_indexes[0]].index
    current = items[index]
    for following in items[index + 1:]:
        if following.level <= current.level:
            return following.index
    return chapter.end


def _path(chapter_dir: Path, heading: Heading) -> Path:
    return chapter_dir / f"{heading.number}_{safe_name(_title(heading.line))}.md"


def _write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _prepare(skill_dir: Path, force: bool) -> Path:
    references = skill_dir / "references"
    if references.exists():
        marker = references / MARKER
        if not force:
            raise RuntimeError(f"Output exists: {references}. Pass --force to replace it.")
        if not marker.is_file():
            raise RuntimeError(
                f"Refusing to replace {references}: it was not marked as generated by Book2Skill."
            )
        if references.resolve().parent != skill_dir.resolve():
            raise RuntimeError("Unsafe references path")
        shutil.rmtree(references)
    references.mkdir(parents=True)
    return references


def build_references(text: str, skill_dir: Path, *, force: bool = False) -> BuildResult:
    lines = text.split("\n")
    detected = chapters(lines)
    if not detected:
        raise RuntimeError(
            "No numbered chapters detected. Expected 第 N 章, Chapter N, or N. Title."
        )
    references = _prepare(skill_dir.resolve(), force)
    written: list[Path] = []
    index_lines = ["# 章节索引", ""]
    preface = lines[:detected[0].start]
    if any(line.strip() for line in preface):
        preface_path = references / "00_前置内容.md"
        _write(preface_path, preface)
        written.append(preface_path)
        index_lines.append(f"- [前置内容]({preface_path.name})")

    for chapter in detected:
        chapter_dir = references / f"{chapter.number:02d}_{safe_name(chapter.title)}"
        items = _headings(lines, chapter)
        first = items[0].index if items else chapter.end
        chapter_file = chapter_dir / f"{chapter.number:02d}_{safe_name(chapter.title)}.md"
        chapter_lines = list(lines[chapter.start:first])
        direct = [item for item in items if item.level == 1]
        if direct:
            chapter_lines.extend(["", "## 子章节"])
            for item in direct:
                target = _path(chapter_dir, item)
                chapter_lines.append(f"- [{item.number} {_title(item.line)}]({target.name})")
        _write(chapter_file, chapter_lines)
        written.append(chapter_file)
        index_lines.append(
            f"- [{chapter.number} {chapter.title}]({chapter_dir.name}/{chapter_file.name})"
        )
        for index, item in enumerate(items):
            content = list(lines[item.index:_end(chapter, items, index)])
            content = _split_heading(content[0], item.number) + content[1:]
            child_indexes = _children(items, index)
            if child_indexes:
                content.extend(["", "## 子章节"])
                for child_index in child_indexes:
                    child = items[child_index]
                    target = _path(chapter_dir, child)
                    content.append(f"- [{child.number} {_title(child.line)}]({target.name})")
            target = _path(chapter_dir, item)
            _write(target, content)
            written.append(target)

    index_path = references / "index.md"
    _write(index_path, index_lines)
    written.insert(0, index_path)
    (references / MARKER).write_text(
        json.dumps({"schema_version": 1, "generator": "book2skill"}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return BuildResult(references, len(detected), tuple(written))
